---
  name: Checks
  
  on: [push]
  
  jobs:
    test-lint:
      name: Test and Lint
      runs-on: ubuntu-latest  # Updated to latest version
      steps:
        - name: Checkout
          uses: actions/checkout@v3  # Updated to v3
  
        - name: Login to Docker Hub
          uses: docker/login-action@v2  # Updated to v2
          with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
  
        - name: Test
          run: docker compose run --rm app sh -c "python manage.py test"
  
        - name: Lint
          run: docker compose run --rm app sh -c "flake8"
  